"""SQLAlchemy models for proposal generation run history."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from sqlalchemy import DateTime, Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from storage.db import Base


def utc_now() -> datetime:
    """Return a timezone-aware timestamp for audit fields."""
    return datetime.now(timezone.utc)


class RunRecord(Base):
    """A single proposal generation run."""

    __tablename__ = "runs"

    id: Mapped[int] = mapped_column(primary_key=True)
    run_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    status: Mapped[str] = mapped_column(String(32), default="created")
    session_id: Mapped[str | None] = mapped_column(String(128))
    workflow_version: Mapped[str | None] = mapped_column(String(64))
    prompt_version: Mapped[str | None] = mapped_column(String(64))
    model_name: Mapped[str | None] = mapped_column(String(128))
    input_brief: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    token_usage: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    approximate_cost: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        onupdate=utc_now,
    )

    node_outputs: Mapped[list[NodeOutput]] = relationship(
        back_populates="run",
        cascade="all, delete-orphan",
    )
    agent_outputs: Mapped[list[AgentOutput]] = relationship(
        back_populates="run",
        cascade="all, delete-orphan",
    )
    proposal_outputs: Mapped[list[ProposalOutput]] = relationship(
        back_populates="run",
        cascade="all, delete-orphan",
    )
    errors: Mapped[list[ErrorRecord]] = relationship(
        back_populates="run",
        cascade="all, delete-orphan",
    )


class NodeOutput(Base):
    """Input and output snapshot for one deterministic workflow node."""

    __tablename__ = "node_outputs"

    id: Mapped[int] = mapped_column(primary_key=True)
    run_id: Mapped[str] = mapped_column(ForeignKey("runs.run_id"), index=True)
    node_name: Mapped[str] = mapped_column(String(128))
    input_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    output_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    token_usage: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)

    run: Mapped[RunRecord] = relationship(back_populates="node_outputs")


class AgentOutput(Base):
    """Structured output generated by a named agent."""

    __tablename__ = "agent_outputs"

    id: Mapped[int] = mapped_column(primary_key=True)
    run_id: Mapped[str] = mapped_column(ForeignKey("runs.run_id"), index=True)
    agent_name: Mapped[str] = mapped_column(String(128))
    output_type: Mapped[str | None] = mapped_column(String(128))
    output_payload: Mapped[dict[str, Any]] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)

    run: Mapped[RunRecord] = relationship(back_populates="agent_outputs")


class ProposalOutput(Base):
    """Final exported proposal artifacts for a run."""

    __tablename__ = "proposal_outputs"

    id: Mapped[int] = mapped_column(primary_key=True)
    run_id: Mapped[str] = mapped_column(ForeignKey("runs.run_id"), index=True)
    markdown_path: Mapped[str | None] = mapped_column(String(512))
    pdf_path: Mapped[str | None] = mapped_column(String(512))
    docx_path: Mapped[str | None] = mapped_column(String(512))
    content_hash: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)

    run: Mapped[RunRecord] = relationship(back_populates="proposal_outputs")


class ErrorRecord(Base):
    """Error details captured during a run."""

    __tablename__ = "error_records"

    id: Mapped[int] = mapped_column(primary_key=True)
    run_id: Mapped[str] = mapped_column(ForeignKey("runs.run_id"), index=True)
    step_name: Mapped[str | None] = mapped_column(String(128))
    error_type: Mapped[str] = mapped_column(String(128))
    error_message: Mapped[str] = mapped_column(Text)
    stack_trace: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)

    run: Mapped[RunRecord] = relationship(back_populates="errors")
